version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    
  nginx: 
    restart: always
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"