
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
permissions:
  - object: /scripts
    pattern: "**"
    owner: root
    mode: 755
    type:
      - file
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 100
      runas: root