version: '3.3'
services:
    web:
     depends_on:
       - nginx
     restart: always
     build:
        context: .
        dockerfile: Dockerfile
     
        
    nginx:
     restart: always
     image: nginx:latest
     volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
     ports:
        - 80:80
