version: '3'
services:
      
  resp1:
    image: server3:latest
    ports:
     - "80"
   
      
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - resp1
    ports:
      - "8080:80"   